site_name: FFT Benchmarking
site_description: 'A collection of resources for learning about FFTs and benchmarking techniques.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/fft-benchmarking/'
repo_url: 'https://github.com/dmccreary/fft-benchmarking'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - About: about.md
  - Course Description: course-description.md

  - Learning Graph:
    - Intro: learning-graph/index.md
    - Course Concepts: learning-graph/course-concepts-v1.md
    - Concept Taxonomy: learning-graph/concept-taxonomy.md
    - Taxonomy Distribution: learning-graph/taxonomy-distribution.md
    - Quality Assessment: learning-graph/quality-assessment.md
    - Quality Metrics: learning-graph/quality-metrics.md
    - Summary: learning-graph/LEARNING-GRAPH-SUMMARY.md
  
  - Tutorials:
      - Tutorial 1: tutorials/tutorial-1.md
  - Cornel Labs FFT on the Pico: cornell-labs/pico-example.md
  - MicroSims:
    - MicroSims Overview: sims/index.md
    - Learning Graph: sims/learning-graph/index.md
    - FFT History Timeline: sims/timeline/index.md
  - Glossary: glossary.md
  - How We Built This Site: how-we-built-this-site.md
  - References: references.md
  - License: license.md
  - Contact: contact.md
 
# Dan's Microsite Standards from here down

theme:
  name: material
  extra_css:
    - styles/custom.css
  logo: img/logo.png
  favicon: img/favicon.png
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
extra_css:
   - css/extra.css
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX